import { AdminLoginParams, AdminGetListParams, AdminCreateParams, AdminUpdateParams, TermGetListParams, PromptGetListParams, PromptHistoryGetListParams, PromptUpdateParams, AdminPasswordUpdateParams, UnitPriceGetListParams } from './adminApi.types';
export declare function adminLogin(params: AdminLoginParams): Promise<unknown[]>;
export declare function adminGetList(params: AdminGetListParams): Promise<unknown[]>;
export declare function adminCreate(params: AdminCreateParams): Promise<unknown[]>;
export declare function adminUpdate(params: AdminUpdateParams): Promise<unknown[]>;
export declare function adminPasswordUpdate(params: AdminPasswordUpdateParams): Promise<unknown[]>;
export declare function termGetList(): Promise<unknown[]>;
export declare function termUpdate(params: TermGetListParams): Promise<unknown[]>;
export declare function promptGetList(params: PromptGetListParams): Promise<unknown[]>;
export declare function promptHistoryGetList(params: PromptHistoryGetListParams): Promise<unknown[]>;
export declare function promptUpdate(params: PromptUpdateParams): Promise<unknown[]>;
export declare function unitPriceGetList(params: UnitPriceGetListParams): Promise<unknown[]>;
